### PR TITLE
fix: opened sockets number overflow maxSockets, when socket timeouts …

### LINKED ISSUE #36: Number of opened sessions overflow maxSockets limitation after timeout
I've encountered this problem on node 0.10.43 and using https.
Immediately after **timeout** event being emited (`ECONNRESET`), **close** event is emited as well, so `removeSocket `function is called twice.

For one of them, socket is removed ad destroyed from socket pool, but for another one, socket is not found on sockets pool so it is not removed and destroyed. Regardless socket being present on socket pool, new socket is created unconditionally, which result in:

**first call:** 1 socket destroyed 1 socket created
**second call:** 0 socket destroyed 1 socket created

After all, there is +1 socket opened after such events happen, there should be some maxSocket check condition before creating new socket.

### PR DESCRIPTION
**Pull request by pangorgo**
closes #36

### CODE REVIEW

**Comment by fengmk2** [comment]
Can you add a test case to reappear this problem?

**Comment by pangorgo** [comment]
Yes, I'll try to reproduce it

**Comment by pangorgo** [comment]
done

**Comment by fengmk2** [comment]
LGTM. But why this only happen on 0.10.43?

**Comment by fengmk2** [comment]
release 2.1.0

**Pull request merged**
