### PR TITLE
fix: ssl socket leak

### PR DESCRIPTION
**Pull request by saperal**
-closes:#32

### CODE REVIEW

**Comment by fengmk2** [comment]
https://github.com/node-modules/agentkeepalive/pull/33/files#diff-5f7fb0850412c6be189faeddea6c5359R226 `createSocket()` will do the `_extend` logic.

**Comment by saperal** [comment]
It extends it's own copy of `options`.
On a subsequent request, when `addRequest() `is called. It is called with the options specified by `https.request(options) ` which don't have the ca property.

**Comment by fengmk2** [comment]
@saperal Can you add a test case for this change?

And you can also send a pr for nodejs itself too. https://github.com/nodejs/node/blob/master/lib/_http_agent.js#L108

**Comment by fengmk2** [comment]
@saperal nice move! I will merge this soon. https://github.com/nodejs/node/pull/5713/files

**Comment by fengmk2** [comment]
Land 88d1e1ee167f28819edce7349d0155b91c1a0d75

**Comment by fengmk2** [comment]
2.1.1

**Pull request closed without merging**
