### PR TITLE
fix(types): correct `Https` constructor argument

### PR DESCRIPTION
**Pull request by SimenB**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by BlackDark** [comment]
TypeScript complains about not available option `rejectUnauthorized`. 
Would be nice if it could be merged and released :)

**Comment by SimenB** [comment]
Any chance of a release as well? 🙂

**Comment by andiradulescu** [comment]
@fengmk2 can you create a new release? Thanks in advance!

**Comment by bermr** [comment]
hey guys! any plans on releasing?

**Comment by insanehong** [comment]
Any plans for a new release?

**Comment by fengmk2** [comment]
4.1.4 release

**Pull request merged**
