### PR TITLE
Handle ipv6 addresses in host-header correctly with TLS

### PR DESCRIPTION
**Pull request by mattiash**
When a url uses an ipv6-addresses as the host part, the host-header of the request will be

[::1]:3000

(for ipv6 address ::1). To verify the IP address against a TLS certificate, we need to extract the
IP-address correctly.

Requires node with https://github.com/nodejs/node/issues/14736 resolved to work.

Resolves issue #52

### CODE REVIEW

**Comment by fengmk2** [comment]
@mattiash Nice work! Can you add a test case for this bug fix?

**Comment by mattiash** [comment]
I have now added more tests that seem to increase the total coverage by 1.18%. codecov/patch fails because the tests do not cover one of the lines in my patch. That line handles the case where the host/port contains a '[' but no ']', which is a broken url that will never work in practice, but my patch needs to handle that case without crashing.

Is there anything else holding this back?

**Comment by mattiasholmlund** [comment]
The node-project accepted my PR for nodejs/node#14736. It contains the same code as this PR. Can this be merged now?

**Comment by mattiasholmlund** [comment]
I would really like to have this fix merged. Is there anything else I can do?

**Comment by mattiasholmlund** [comment]
The nodejs-project released version 8.10.0 (LTS) today which includes my patch for ipv6 addresses in certificates. I have updated this PR with checks for if IPv6 is available on the test-environment and if a version of node with my fixes is used. All tests now pass on both travis and appveyor. The coverage decreases in the codecov report, but that is (probably) because codecov seems to run the tests on an environment with IPv6 disabled and then the IPv6 tests will not run and thus the code will be untested. appveyor runs with IPv6 enabled, so the code is actually tested.

I would be very happy if you could merge this PR and make a new release...

**Comment by fengmk2** [comment]
@mattiash @mattiasholmlund Thanks a lot!

**Comment by fengmk2** [comment]
3.4.1 Released

**Pull request merged**
